version: '3.4'

services:
  jenkins_service:
    image: my_jenkins:latest
    deploy:
      replicas: 1
      restart_policy: 
        condition: any
      placement:
        constraints:
           - node.hostname == default
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:5000
volumes:
  jenkins_data:
    driver: local
