version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: my_password
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: my_existing_network