version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    networks:
      - backend
    environment: 
      MYSQL_ROOT_PASSWORD: my_password
      
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - frontend

networks:
  frontend:
    driver: bridge

  backend:
    driver: bridge