version: '3.4'

services:
  my_service_name:
    image: httpd:latest
    configs:
      - swarm_cert_name_config:
        source: swarm_cert_name_config
        target: ./new_target_directory_configs/test.crt
    secrets:
      - swarm_cert_name_secret:
        source: swarm_cert_name_secret
        target: ./new_target_directory_secrets/test.crt
    deploy:
      mode: replicated
      replicas: 2
      labels:
        com.docker.descr: "test description"
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 50M
        reservations:
          cpus: '0.10'
      update_config:
        parallelism: 1
        delay: 10s
        monitor: 5s

configs:
  swarm_cert_name_config:
    file: ./my_swarm_ca.crt

secrets:
  swarm_cert_name_secret:
    file: ./my_swarm_ca.crt